services:
  - type: web
    name: churn-predictor
    env: python
    runtime: python-3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: churn
    plan: free
    autoDeploy: true

